In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv("/content/orders.csv")
time = pd.read_csv("/content/messages.csv")

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
date.info()
#the date is stored in string - we cant perform the functions that we want to if we have the column name as string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [9]:
#similarly for time - the column has enteries in the form of string
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [10]:
#converting the string into datetime
date['date'] = pd.to_datetime(date['date'])

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
date['date_year'] = date['date'].dt.year

In [13]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [15]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [17]:
date['month_name'] = date['date'].dt.month_name()

In [18]:
date.head()

        date  product_id  city_id  orders  date_year  date_month month_name
0 2019-12-10        5628       25       3       2019          12   December
1 2018-08-15        3646       14     157       2018           8     August
2 2018-10-23        1859       25       1       2018          10    October
3 2019-08-17        7292       25       1       2019           8     August
4 2019-01-06        4344       25       3       2019           1    January

In [19]:
date['date_day'] = date['date'].dt.day

In [20]:
date['day_dow'] = date['date'].dt.day_of_week

In [21]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,month_name,date_day,day_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [26]:
date['day_name'] = date['date'].dt.day_name()
date.drop(columns = ['product_id' , 'city_id','orders']).head()

        date  date_year  date_month month_name  date_day  day_dow   day_name
0 2019-12-10       2019          12   December        10        1    Tuesday
1 2018-08-15       2018           8     August        15        2  Wednesday
2 2018-10-23       2018          10    October        23        1    Tuesday
3 2019-08-17       2019           8     August        17        5   Saturday
4 2019-01-06       2019           1    January         6        6     Sunday

In [27]:
date['date_is_weekend'] = np.where(date['day_name'].isin(['Sunday' , 'Saturday']) , 1 ,0)
date.drop(columns = ['product_id' , 'city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,day_dow,day_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [29]:
date['year_week'] = date['date'].dt.weekday
date.drop(columns = ['product_id' , 'city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,day_dow,day_name,date_is_weekend,year_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,6

In [31]:
#EXTRACT TIME ELAPSED BETWEEN DATES
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2025, 11, 24, 9, 51, 36, 681354)

In [32]:
today- date['date']

0     2176 days 09:51:36.681354
1     2658 days 09:51:36.681354
2     2589 days 09:51:36.681354
3     2291 days 09:51:36.681354
4     2514 days 09:51:36.681354
                 ...
995   2604 days 09:51:36.681354
996   2545 days 09:51:36.681354
997   2393 days 09:51:36.681354
998   2458 days 09:51:36.681354
999   2232 days 09:51:36.681354
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
(today - date['date']).dt.days

0      2176
1      2658
2      2589
3      2291
4      2514
       ...
995    2604
996    2545
997    2393
998    2458
999    2232
Name: date, Length: 1000, dtype: int64

In [38]:
months_passed = np.round((today - date['date']) / np.timedelta64(30, 'D'))
months_passed

0      73.0
1      89.0
2      86.0
3      76.0
4      84.0
       ...
995    87.0
996    85.0
997    80.0
998    82.0
999    74.0
Name: date, Length: 1000, dtype: float64

In [39]:
time['date'] = pd.to_datetime(time['date'])

In [44]:
time['hoour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

time.head()

,date,msg,hoour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0