In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [5]:
df = pd.read_csv("/content/train (1).csv")[['Age','Pclass','SibSp','Parch' , 'Survived']]

In [6]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [7]:
df.dropna(inplace = True)

In [8]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [9]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [10]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [12]:
np.mean(cross_val_score(LogisticRegression() , X  , y , scoring = 'accuracy' , cv = 20))

np.float64(0.6933333333333332)

In [13]:
X['Family_size'] = X['SibSp'] + X['Parch'] +1

In [14]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [15]:
def myfunc(n):
  if n ==1:
    return 0
  elif n>=1 and n<=4:
    return 1
  else:
    return 2

In [16]:
myfunc(3)

1

In [18]:
X['family_type'] = X['Family_size'].apply(myfunc)

In [19]:
X.drop(columns = ['SibSp','Parch','Family_size'] , inplace = True)

In [20]:
X.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [21]:
np.mean(cross_val_score(LogisticRegression() , X  , y , scoring = 'accuracy' , cv = 20))

np.float64(0.7003174603174602)

In [22]:
#Feature splitting
df = pd.read_csv("/content/train (1).csv")

In [23]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [24]:
df['Title'] = df['Name'].str.split(', ' , expand = True)[1].str.split(',' , expand = True)[0]

In [25]:
df[['Title','Name']]

                                          Title                                               Name
0                               Mr. Owen Harris                            Braund, Mr. Owen Harris
1    Mrs. John Bradley (Florence Briggs Thayer)  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                   Miss. Laina                             Heikkinen, Miss. Laina
3            Mrs. Jacques Heath (Lily May Peel)       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Mr. William Henry                           Allen, Mr. William Henry
..                                          ...                                                ...
886                                 Rev. Juozas                              Montvila, Rev. Juozas
887                        Miss. Margaret Edith                       Graham, Miss. Margaret Edith
888              Miss. Catherine Helen "Carrie"           Johnston, Miss. Catherine Helen "Carrie"
889                             Mr. Karl Howell                              Behr, Mr. Karl Howell
890                                 Mr. Patrick                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [27]:
df['is_married'] = 0
df['is_married'].loc[df['Title']=='Mrs']

Series([], Name: is_married, dtype: int64)

In [28]:
df['is_married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: is_married, Length: 891, dtype: int64