In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [46]:
df = np.round(pd.read_csv("/content/50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9) #for getting the sae set of random numbers every time we use the code - fix Randomness
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [47]:
#from the df we are removing the profit column as it is the orginal output
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [6]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[4,2] = np.nan

/tmp/ipython-input-235786511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipython-input-235786511.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipython-input-235786511.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[4,2] = np.nan

In [7]:
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [27]:
#created a new new table where the nan values are replaced with eans of there respective columns
df1 = pd.DataFrame()
df1['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean(0))
df1['Administration'] = df['Administration'].fillna(df['Administration'].mean(0))
df1['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean(0))

In [28]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [29]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2

#this is mainly done to predict the value of the orignal nan value in our table

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [30]:
X = df2.iloc[[0,2,3,4] , 1:3]
y = df2.iloc[[0,2,3,4] , 0]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [31]:
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [32]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))  # changing pandas to numpy and converting to an array of row = 1 and column = 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [34]:
df2.iloc[1,0] = 23.14

In [35]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [36]:
df.iloc[3,1] = np.nan

/tmp/ipython-input-3200624742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan

In [37]:
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [38]:
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [42]:
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [44]:
df2.iloc[3,1] = 11.06

In [48]:
df2.iloc[-1,-1] = np.nan

In [51]:
X = df2.iloc[[0,1,2,3],0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [52]:
y = df2.iloc[[0,1,2,3],2]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [53]:
lr.fit(X,y)
lr.predict(df.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [54]:
df2.iloc[-1,-1] = 31.56

In [55]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [56]:
df2-df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [57]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

In [58]:
df3

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [59]:
X = df3.iloc[[0,2,3,4],1:]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.06            26.00
44           15.00            31.56

In [60]:
y = df3.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [61]:
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [62]:
df3.iloc[1,0] = 23.78

In [63]:
X = df3.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.78            20.00
2       15.00            41.00
44       2.00            31.56

In [64]:
y = df.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [65]:
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [66]:
df3.iloc[3,1] = 11.22

In [67]:
X = df3.iloc[[0,1,2,3],0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.78            5.00
2       15.00           10.00
14      12.00           11.22

In [71]:
y = df3.iloc[[0,1,2,3],-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [72]:
lr.fit(X,y)
lr.predict(df3.iloc[-1,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [73]:
df3.iloc[-1,-1] = 38.87

In [74]:
df3-df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.64            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.16             0.00
44       0.00            0.00             7.31

In [75]:
df4 = df3.copy()

In [83]:
df4

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            38.87

In [90]:
from sklearn.linear_model import LinearRegression
import numpy as np

lr = LinearRegression()

# df4 = dataframe you are iteratively imputing
# df  = original dataframe (to check original NaNs)

for col in df4.columns:
    print(f"\nImputing column: {col}")

    for row in df4.index:
        if np.isnan(df.loc[row, col]):   # Only impute original NaN positions

            # X: all columns except the one being imputed
            X = df4.drop(columns=[col])
            y = df4[col]

            # Use only rows where y is known
            mask = ~y.isna()
            X_train = X.loc[mask]
            y_train = y.loc[mask]

            # Prepare the prediction input (single row, drop the target col)
            X_pred = X.loc[row].values.reshape(1, -1)

            # Fit & predict
            lr.fit(X_train, y_train)
            predicted_value = lr.predict(X_pred)[0]

            # Update df4 iteratively
            df4.loc[row, col] = predicted_value

            print(f"  filled row {row} with {predicted_value:.4f}")

Imputing column: R&D Spend

Imputing column: Administration

Imputing column: Marketing Spend

In [91]:
df4

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            38.87